### ISSUE TITLE
About the choices

### ISSUE THREAD

**Issue by tzc-nydzsf** [sng-panghaoyuan/jie#4]
why there isn't the choice fentou in 5.2.0/team

I think you needn't add a choice, but add something when you attack, like this:

```
请你选择攻击对象个数：
k(input)
请你选择攻击对象(k个正整数)：
a1 a2 …… ak
```

of course, k has a limit, you know.

**Comment by tzc-nydzsf** [comment]
@CHHHOCHHH

**Comment by CHHHOCHHH** [comment]
> @CHHHOCHHH

i don’t think it necessary.

**Comment by CHHHOCHHH** [comment]
@tzc-nydzsf

**Comment by tzc-nydzsf** [comment]
> > @CHHHOCHHH
> 
> i don’t think it necessary.

@CHHHOCHHH  but why?

**Comment by CHHHOCHHH** [comment]
> > > @CHHHOCHHH
> > 
> > 
> > i don’t think it necessary.
> 
> @CHHHOCHHH but why?

@tzc-nydzsf no why

**Comment by tzc-nydzsf** [comment]
> > > > @CHHHOCHHH
> > > 
> > > 
> > > i don’t think it necessary.
> > 
> > 
> > @CHHHOCHHH but why?
> 
> @tzc-nydzsf no why

@CHHHOCHHH /no
